// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/Volumes/MacStorage/UserData/0devprojects/sb-cortextos-fork/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/Volumes/MacStorage/UserData/0devprojects/sb-cortextos-fork",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/Users/sauravb/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/Volumes/MacStorage/UserData/0devprojects/sb-cortextos-fork",
        CTX_PROJECT_ROOT: "/Volumes/MacStorage/UserData/0devprojects/sb-cortextos-fork",
        CTX_ORG: process.env.CTX_ORG || "sb-personal",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "npm",
      args: "run dev",
      cwd: "/Volumes/MacStorage/UserData/0devprojects/sb-cortextos-fork/dashboard",
      env: {
        PORT: process.env.PORT || '3010',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      // Fleet-resilience cleanup B: was 50, dropped to 3 after the 2026-05-14
      // post-mortem traced a 327-PM2-restart thrash to the dashboard hitting
      // EADDRINUSE on :3000 forever. PR #43 added a port-probe to fail fast
      // INSIDE the dashboard process; this cap stops PM2 from hammering an
      // unrecoverable failure for hours. Operator-side launchd plists or
      // external PM2 registries that supervise dashboard outside the repo
      // need a parallel fix — see docs_sb/runbooks/dashboard-supervisor-investigation.md.
      max_restarts: 3,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
